/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

import ui.components.textfield.CustomRoundedTextField;

/**
 *
 * @author TRAN LONG VU
 */
public class Form_StaffManagement extends javax.swing.JPanel {

    /**
     * Creates new form Form_StaffManagement
     */
    public Form_StaffManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_North = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        pnl_Center = new javax.swing.JPanel();
        pnl_Left = new javax.swing.JPanel();
        pnl_FisrtName = new javax.swing.JPanel();
        lbl_FirstName = new javax.swing.JLabel();
        txt_FisrtName = new ui.components.textfield.CustomRoundedTextField();
        pnl_LastName = new javax.swing.JPanel();
        lbl_LastName = new javax.swing.JLabel();
        txt_LastName = new ui.components.textfield.CustomRoundedTextField();
        pnl_Phone = new javax.swing.JPanel();
        lbl_Phone = new javax.swing.JLabel();
        txt_Phone = new ui.components.textfield.CustomRoundedTextField();
        pnl_Email = new javax.swing.JPanel();
        lbl_Email = new javax.swing.JLabel();
        txt_Email = new ui.components.textfield.CustomRoundedTextField();
        pnl_Address = new javax.swing.JPanel();
        lbl_Address = new javax.swing.JLabel();
        txt_Address = new ui.components.textfield.CustomRoundedTextField();
        pnl_Password = new javax.swing.JPanel();
        lbl_Password = new javax.swing.JLabel();
        txt_Password = new ui.components.textfield.CustomRoundedTextField();
        pnl_UserName = new javax.swing.JPanel();
        lbl_UserName = new javax.swing.JLabel();
        txt_UserName = new ui.components.textfield.CustomRoundedTextField();
        pnl_Gender = new javax.swing.JPanel();
        lbl_Gender = new javax.swing.JLabel();
        cbx_Gender = new ui.components.combobox.StyledComboBox();
        pnl_DateJoin = new javax.swing.JPanel();
        lbl_DateJoin = new javax.swing.JLabel();
        calender_DateJoin = new ui.components.calendar.CustomCalendar();
        pnl_BirthDate = new javax.swing.JPanel();
        lbl_BirthDate = new javax.swing.JLabel();
        calendar_BirthDate = new ui.components.calendar.CustomCalendar();
        btn_UploadAvatar = new ui.components.button.ButtonCustom();
        lbl_UploadAvatar = new ui.components.label.LabelImage();
        pnl_Right = new javax.swing.JPanel();
        pnl_NameSearch = new javax.swing.JPanel();
        lbl_NameSearch = new javax.swing.JLabel();
        txt_NameSearch = new ui.components.textfield.CustomRoundedTextField();
        pnl_IDSearch = new javax.swing.JPanel();
        lbl_IDSearch = new javax.swing.JLabel();
        txt_IDSearch = new ui.components.textfield.CustomRoundedTextField();
        pnl_PhoneSearch = new javax.swing.JPanel();
        lbl_PhoneSearch = new javax.swing.JLabel();
        txt_PhoneSearch = new ui.components.textfield.CustomRoundedTextField();
        pnl_GenderSearch = new javax.swing.JPanel();
        lbl_GenderSearch = new javax.swing.JLabel();
        cbx_GenderSearch = new ui.components.combobox.StyledComboBox();
        btn_Search = new ui.components.button.ButtonCustom();
        pnl_South = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customTable1 = new ui.components.table.CustomTable();
        pButton = new javax.swing.JPanel();
        btnAdd = new ui.components.button.ButtonCustom();
        btnUpdate = new ui.components.button.ButtonCustom();
        btnImport = new ui.components.button.ButtonCustom();
        btnExport = new ui.components.button.ButtonCustom();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnl_North.setBackground(new java.awt.Color(255, 255, 255));
        pnl_North.setLayout(new java.awt.BorderLayout());

        lbl_Title.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Title.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(127, 122, 239));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText(" QUẢN LÝ NHÂN VIÊN");
        pnl_North.add(lbl_Title, java.awt.BorderLayout.CENTER);

        add(pnl_North, java.awt.BorderLayout.PAGE_START);

        pnl_Center.setLayout(new java.awt.BorderLayout());

        pnl_Left.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Left.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(102, 102, 255))); // NOI18N
        pnl_Left.setLayout(null);

        pnl_FisrtName.setBackground(new java.awt.Color(255, 255, 255));

        lbl_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_FirstName.setText("Họ:");

        txt_FisrtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FisrtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_FisrtNameLayout = new javax.swing.GroupLayout(pnl_FisrtName);
        pnl_FisrtName.setLayout(pnl_FisrtNameLayout);
        pnl_FisrtNameLayout.setHorizontalGroup(
            pnl_FisrtNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FisrtNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(txt_FisrtName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_FisrtNameLayout.setVerticalGroup(
            pnl_FisrtNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FisrtNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_FisrtNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FirstName)
                    .addComponent(txt_FisrtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Left.add(pnl_FisrtName);
        pnl_FisrtName.setBounds(30, 30, 350, 41);

        pnl_LastName.setBackground(new java.awt.Color(255, 255, 255));

        lbl_LastName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_LastName.setText("Tên:");

        txt_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LastNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_LastNameLayout = new javax.swing.GroupLayout(pnl_LastName);
        pnl_LastName.setLayout(pnl_LastNameLayout);
        pnl_LastNameLayout.setHorizontalGroup(
            pnl_LastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LastNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_LastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(txt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_LastNameLayout.setVerticalGroup(
            pnl_LastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LastNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_LastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_LastName)
                    .addComponent(txt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Left.add(pnl_LastName);
        pnl_LastName.setBounds(390, 30, 320, 41);

        pnl_Phone.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Phone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_Phone.setText("Số điện thoại:");

        txt_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_PhoneLayout = new javax.swing.GroupLayout(pnl_Phone);
        pnl_Phone.setLayout(pnl_PhoneLayout);
        pnl_PhoneLayout.setHorizontalGroup(
            pnl_PhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Phone)
                .addGap(18, 18, 18)
                .addComponent(txt_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_PhoneLayout.setVerticalGroup(
            pnl_PhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_PhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Phone)
                    .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Left.add(pnl_Phone);
        pnl_Phone.setBounds(30, 70, 360, 41);

        pnl_Email.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_Email.setText("Email:");

        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_EmailLayout = new javax.swing.GroupLayout(pnl_Email);
        pnl_Email.setLayout(pnl_EmailLayout);
        pnl_EmailLayout.setHorizontalGroup(
            pnl_EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_EmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_EmailLayout.setVerticalGroup(
            pnl_EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_EmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Email)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Left.add(pnl_Email);
        pnl_Email.setBounds(390, 70, 320, 41);

        pnl_Address.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Address.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_Address.setText("Địa chỉ:");

        txt_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_AddressLayout = new javax.swing.GroupLayout(pnl_Address);
        pnl_Address.setLayout(pnl_AddressLayout);
        pnl_AddressLayout.setHorizontalGroup(
            pnl_AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AddressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Address)
                .addGap(32, 32, 32)
                .addComponent(txt_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
        );
        pnl_AddressLayout.setVerticalGroup(
            pnl_AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Address)
                    .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Left.add(pnl_Address);
        pnl_Address.setBounds(390, 150, 330, 41);

        pnl_Password.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Password.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_Password.setText("Mật khẩu:");

        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_PasswordLayout = new javax.swing.GroupLayout(pnl_Password);
        pnl_Password.setLayout(pnl_PasswordLayout);
        pnl_PasswordLayout.setHorizontalGroup(
            pnl_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Password)
                .addGap(15, 15, 15)
                .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_PasswordLayout.setVerticalGroup(
            pnl_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Password)
                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Left.add(pnl_Password);
        pnl_Password.setBounds(390, 110, 330, 41);

        pnl_UserName.setBackground(new java.awt.Color(255, 255, 255));

        lbl_UserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_UserName.setText("Tài khoản:");

        txt_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_UserNameLayout = new javax.swing.GroupLayout(pnl_UserName);
        pnl_UserName.setLayout(pnl_UserNameLayout);
        pnl_UserNameLayout.setHorizontalGroup(
            pnl_UserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_UserName)
                .addGap(41, 41, 41)
                .addComponent(txt_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );
        pnl_UserNameLayout.setVerticalGroup(
            pnl_UserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_UserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_UserName)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Left.add(pnl_UserName);
        pnl_UserName.setBounds(30, 110, 350, 41);

        pnl_Gender.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Gender.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_Gender.setText("Giới tính:");

        cbx_Gender.setPreferredSize(new java.awt.Dimension(72, 34));
        cbx_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_GenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_GenderLayout = new javax.swing.GroupLayout(pnl_Gender);
        pnl_Gender.setLayout(pnl_GenderLayout);
        pnl_GenderLayout.setHorizontalGroup(
            pnl_GenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(cbx_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnl_GenderLayout.setVerticalGroup(
            pnl_GenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GenderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_GenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_Gender, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbl_Gender))
                .addContainerGap())
        );

        pnl_Left.add(pnl_Gender);
        pnl_Gender.setBounds(30, 150, 370, 42);

        pnl_DateJoin.setBackground(new java.awt.Color(255, 255, 255));

        lbl_DateJoin.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_DateJoin.setText("Ngày làm:");

        javax.swing.GroupLayout pnl_DateJoinLayout = new javax.swing.GroupLayout(pnl_DateJoin);
        pnl_DateJoin.setLayout(pnl_DateJoinLayout);
        pnl_DateJoinLayout.setHorizontalGroup(
            pnl_DateJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DateJoinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_DateJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calender_DateJoin, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
        );
        pnl_DateJoinLayout.setVerticalGroup(
            pnl_DateJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_DateJoinLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(pnl_DateJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_DateJoin)
                    .addComponent(calender_DateJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnl_Left.add(pnl_DateJoin);
        pnl_DateJoin.setBounds(390, 190, 320, 40);

        pnl_BirthDate.setBackground(new java.awt.Color(255, 255, 255));

        lbl_BirthDate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_BirthDate.setText("Ngày sinh:");

        javax.swing.GroupLayout pnl_BirthDateLayout = new javax.swing.GroupLayout(pnl_BirthDate);
        pnl_BirthDate.setLayout(pnl_BirthDateLayout);
        pnl_BirthDateLayout.setHorizontalGroup(
            pnl_BirthDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BirthDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_BirthDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(calendar_BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_BirthDateLayout.setVerticalGroup(
            pnl_BirthDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BirthDateLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbl_BirthDate)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BirthDateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(calendar_BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_Left.add(pnl_BirthDate);
        pnl_BirthDate.setBounds(30, 190, 350, 40);

        btn_UploadAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upload_image.png"))); // NOI18N
        btn_UploadAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UploadAvatarActionPerformed(evt);
            }
        });
        pnl_Left.add(btn_UploadAvatar);
        btn_UploadAvatar.setBounds(739, 200, 70, 30);
        pnl_Left.add(lbl_UploadAvatar);
        lbl_UploadAvatar.setBounds(730, 40, 150, 150);

        pnl_Center.add(pnl_Left, java.awt.BorderLayout.CENTER);

        pnl_Right.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Right.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(102, 102, 255))); // NOI18N

        pnl_NameSearch.setBackground(new java.awt.Color(255, 255, 255));

        lbl_NameSearch.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_NameSearch.setText("Họ và tên:");

        txt_NameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_NameSearchLayout = new javax.swing.GroupLayout(pnl_NameSearch);
        pnl_NameSearch.setLayout(pnl_NameSearchLayout);
        pnl_NameSearchLayout.setHorizontalGroup(
            pnl_NameSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NameSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_NameSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txt_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_NameSearchLayout.setVerticalGroup(
            pnl_NameSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NameSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_NameSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NameSearch)
                    .addComponent(txt_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_IDSearch.setBackground(new java.awt.Color(255, 255, 255));

        lbl_IDSearch.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_IDSearch.setText("Mã nhân viên:");

        txt_IDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_IDSearchLayout = new javax.swing.GroupLayout(pnl_IDSearch);
        pnl_IDSearch.setLayout(pnl_IDSearchLayout);
        pnl_IDSearchLayout.setHorizontalGroup(
            pnl_IDSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_IDSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_IDSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_IDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_IDSearchLayout.setVerticalGroup(
            pnl_IDSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_IDSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_IDSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_IDSearch)
                    .addComponent(txt_IDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_PhoneSearch.setBackground(new java.awt.Color(255, 255, 255));

        lbl_PhoneSearch.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_PhoneSearch.setText("Số điện thoại:");

        txt_PhoneSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhoneSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_PhoneSearchLayout = new javax.swing.GroupLayout(pnl_PhoneSearch);
        pnl_PhoneSearch.setLayout(pnl_PhoneSearchLayout);
        pnl_PhoneSearchLayout.setHorizontalGroup(
            pnl_PhoneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhoneSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_PhoneSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PhoneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_PhoneSearchLayout.setVerticalGroup(
            pnl_PhoneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhoneSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_PhoneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PhoneSearch)
                    .addComponent(txt_PhoneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_GenderSearch.setBackground(new java.awt.Color(255, 255, 255));

        lbl_GenderSearch.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_GenderSearch.setText("Giới tính:");

        cbx_GenderSearch.setPreferredSize(new java.awt.Dimension(72, 34));
        cbx_GenderSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_GenderSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_GenderSearchLayout = new javax.swing.GroupLayout(pnl_GenderSearch);
        pnl_GenderSearch.setLayout(pnl_GenderSearchLayout);
        pnl_GenderSearchLayout.setHorizontalGroup(
            pnl_GenderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GenderSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_GenderSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(cbx_GenderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnl_GenderSearchLayout.setVerticalGroup(
            pnl_GenderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_GenderSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_GenderSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_GenderSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbl_GenderSearch))
                .addContainerGap())
        );

        btn_Search.setText("Tìm kiếm");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_RightLayout = new javax.swing.GroupLayout(pnl_Right);
        pnl_Right.setLayout(pnl_RightLayout);
        pnl_RightLayout.setHorizontalGroup(
            pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(pnl_RightLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_IDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_GenderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_PhoneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_RightLayout.setVerticalGroup(
            pnl_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RightLayout.createSequentialGroup()
                .addComponent(pnl_IDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnl_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_PhoneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_GenderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        pnl_Center.add(pnl_Right, java.awt.BorderLayout.EAST);

        pnl_South.setBackground(new java.awt.Color(255, 255, 255));

        customTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Giới tính", "Ngày sinh", "Số điện thoại", "Email", "Địa chỉ", "Chức vụ", "Ngày vào làm", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(customTable1);

        pButton.setBackground(new java.awt.Color(255, 255, 255));
        pButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("Thêm");
        pButton.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 50));

        btnUpdate.setText("Cập nhật");
        pButton.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 50));

        btnImport.setText("Import");
        pButton.add(btnImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 50));

        btnExport.setText("Export");
        pButton.add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 50));

        javax.swing.GroupLayout pnl_SouthLayout = new javax.swing.GroupLayout(pnl_South);
        pnl_South.setLayout(pnl_SouthLayout);
        pnl_SouthLayout.setHorizontalGroup(
            pnl_SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SouthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(3451, Short.MAX_VALUE))
        );
        pnl_SouthLayout.setVerticalGroup(
            pnl_SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pButton.getAccessibleContext().setAccessibleDescription("");

        pnl_Center.add(pnl_South, java.awt.BorderLayout.PAGE_END);

        add(pnl_Center, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_FisrtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FisrtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FisrtNameActionPerformed

    private void txt_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LastNameActionPerformed

    private void txt_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhoneActionPerformed

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddressActionPerformed

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    private void txt_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserNameActionPerformed

    private void cbx_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_GenderActionPerformed

    private void btn_UploadAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UploadAvatarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_UploadAvatarActionPerformed

    private void txt_NameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameSearchActionPerformed

    private void txt_IDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDSearchActionPerformed

    private void txt_PhoneSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhoneSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhoneSearchActionPerformed

    private void cbx_GenderSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_GenderSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_GenderSearchActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.button.ButtonCustom btnAdd;
    private ui.components.button.ButtonCustom btnExport;
    private ui.components.button.ButtonCustom btnImport;
    private ui.components.button.ButtonCustom btnUpdate;
    private ui.components.button.ButtonCustom btn_Search;
    private ui.components.button.ButtonCustom btn_UploadAvatar;
    private ui.components.calendar.CustomCalendar calendar_BirthDate;
    private ui.components.calendar.CustomCalendar calender_DateJoin;
    private ui.components.combobox.StyledComboBox cbx_Gender;
    private ui.components.combobox.StyledComboBox cbx_GenderSearch;
    private ui.components.table.CustomTable customTable1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_BirthDate;
    private javax.swing.JLabel lbl_DateJoin;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_FirstName;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_GenderSearch;
    private javax.swing.JLabel lbl_IDSearch;
    private javax.swing.JLabel lbl_LastName;
    private javax.swing.JLabel lbl_NameSearch;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_PhoneSearch;
    private javax.swing.JLabel lbl_Title;
    private ui.components.label.LabelImage lbl_UploadAvatar;
    private javax.swing.JLabel lbl_UserName;
    private javax.swing.JPanel pButton;
    private javax.swing.JPanel pnl_Address;
    private javax.swing.JPanel pnl_BirthDate;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_DateJoin;
    private javax.swing.JPanel pnl_Email;
    private javax.swing.JPanel pnl_FisrtName;
    private javax.swing.JPanel pnl_Gender;
    private javax.swing.JPanel pnl_GenderSearch;
    private javax.swing.JPanel pnl_IDSearch;
    private javax.swing.JPanel pnl_LastName;
    private javax.swing.JPanel pnl_Left;
    private javax.swing.JPanel pnl_NameSearch;
    private javax.swing.JPanel pnl_North;
    private javax.swing.JPanel pnl_Password;
    private javax.swing.JPanel pnl_Phone;
    private javax.swing.JPanel pnl_PhoneSearch;
    private javax.swing.JPanel pnl_Right;
    private javax.swing.JPanel pnl_South;
    private javax.swing.JPanel pnl_UserName;
    private ui.components.textfield.CustomRoundedTextField txt_Address;
    private ui.components.textfield.CustomRoundedTextField txt_Email;
    private ui.components.textfield.CustomRoundedTextField txt_FisrtName;
    private ui.components.textfield.CustomRoundedTextField txt_IDSearch;
    private ui.components.textfield.CustomRoundedTextField txt_LastName;
    private ui.components.textfield.CustomRoundedTextField txt_NameSearch;
    private ui.components.textfield.CustomRoundedTextField txt_Password;
    private ui.components.textfield.CustomRoundedTextField txt_Phone;
    private ui.components.textfield.CustomRoundedTextField txt_PhoneSearch;
    private ui.components.textfield.CustomRoundedTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
