/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.dialogs;

import dao.ServicesDAOImpl;
import entities.Service;
import interfaces.ServicesDAO;
import org.apache.poi.ss.usermodel.Row;
import ui.components.table.CustomTableButton;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.util.List;

/**
 *
 * @author TRAN LONG VU
 */
public class Dialog_AddService extends javax.swing.JPanel {
    private String roomID;

    /**
     * Creates new form Dialog_AddService
     */
    public Dialog_AddService(String roomID) {
        this.roomID = roomID;
        initComponents();
        initDataTableService();
        initSearchServices();
    }

    private void initSearchServices() {
        txt_SearchServices.getTextField().getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateSearchServices();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateSearchServices();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateSearchServices();
            }
        });
    }

    private void updateSearchServices() {
        String keyword = txt_SearchServices.getText().trim();
        ServicesDAO servicesDAO = new ServicesDAOImpl();
        List<Service> services = servicesDAO.searchServices(keyword, true);
        displayServicesTable(services);
    }

    private void initDataTableService() {
        ServicesDAO servicesDAO = new ServicesDAOImpl();
        List<Service> services = servicesDAO.findAll();

        lbl_RoomID.setText(roomID);
        displayServicesTable(services);
    }

    private void displayServicesTable(List<Service> services) {
        CustomTableButton.CustomTableModel model = table_ListService.getTableModel();
        model.clearData();

        for (Service service : services) {
            Object[] rowData = {
                    service.getServiceId(),
                    service.getName(),
                    String.format("%,.0f VND", service.getPrice()),
                    service.getDescription(),
                    service.isAvailability() ? "Có sẵn" : "Không có sẵn"
            };
            model.addRow(rowData, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Title = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        lbl_RoomID = new javax.swing.JLabel();
        pnl_Search = new javax.swing.JPanel();
        txt_SearchServices = new ui.components.textfield.SearchTextField();
        pnl_Title_ListService = new javax.swing.JPanel();
        lbl_Title_ListService = new javax.swing.JLabel();
        pnl_ListService = new javax.swing.JPanel();
        table_ListService = new ui.components.table.CustomTableButton();
        table_CartService = new javax.swing.JPanel();
        customTableButton1 = new ui.components.table.CustomTableButton();
        pnl_InforAddService = new javax.swing.JPanel();
        pnl_Title_TotalPrice = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_TotalPrice = new javax.swing.JPanel();
        lbl_TotalPrice_Value = new javax.swing.JLabel();
        btn_Complete = new ui.components.button.ButtonCustom();
        btn_Cancel = new ui.components.button.ButtonCancelCustom();
        btn_AddService = new ui.components.button.ButtonCustom();
        pnl_Title_SelectedService = new javax.swing.JPanel();
        lbl_Title_SelectedService = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Title.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(153, 153, 255));
        lbl_Title.setText("Thêm dịch vụ phòng");

        lbl_RoomID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_RoomID.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout pnl_TitleLayout = new javax.swing.GroupLayout(pnl_Title);
        pnl_Title.setLayout(pnl_TitleLayout);
        pnl_TitleLayout.setHorizontalGroup(
            pnl_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_RoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        pnl_TitleLayout.setVerticalGroup(
            pnl_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_RoomID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(pnl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 30));

        pnl_Search.setBackground(new java.awt.Color(255, 255, 255));

        txt_SearchServices.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_SearchServices.setPlaceholder("Nhập tên dịch vụ...");
        txt_SearchServices.setPlaceholderColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnl_SearchLayout = new javax.swing.GroupLayout(pnl_Search);
        pnl_Search.setLayout(pnl_SearchLayout);
        pnl_SearchLayout.setHorizontalGroup(
            pnl_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SearchLayout.createSequentialGroup()
                .addComponent(txt_SearchServices, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 452, Short.MAX_VALUE))
        );
        pnl_SearchLayout.setVerticalGroup(
            pnl_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SearchLayout.createSequentialGroup()
                .addComponent(txt_SearchServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(pnl_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, 40));

        pnl_Title_ListService.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Title_ListService.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_Title_ListService.setForeground(new java.awt.Color(153, 153, 255));
        lbl_Title_ListService.setText("Danh sách dịch vụ:");

        javax.swing.GroupLayout pnl_Title_ListServiceLayout = new javax.swing.GroupLayout(pnl_Title_ListService);
        pnl_Title_ListService.setLayout(pnl_Title_ListServiceLayout);
        pnl_Title_ListServiceLayout.setHorizontalGroup(
            pnl_Title_ListServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Title_ListServiceLayout.createSequentialGroup()
                .addComponent(lbl_Title_ListService)
                .addGap(0, 699, Short.MAX_VALUE))
        );
        pnl_Title_ListServiceLayout.setVerticalGroup(
            pnl_Title_ListServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Title_ListServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Title_ListService)
                .addContainerGap())
        );

        add(pnl_Title_ListService, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 830, 30));

        pnl_ListService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnl_ListService.setLayout(new java.awt.BorderLayout());

        table_ListService.setColumnNames(new String[] {"Mã dịch vụ", "Tên dịch vụ", "Giá", "Mô tả", "Trạng thái"});
        table_ListService.setHeaderBackgroundColor(new java.awt.Color(153, 153, 255));
        pnl_ListService.add(table_ListService, java.awt.BorderLayout.CENTER);

        add(pnl_ListService, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 860, 220));

        table_CartService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        table_CartService.setLayout(new java.awt.BorderLayout());

        customTableButton1.setColumnNames(new String[] {"Mã dịnh vụ", "Tên dịch vụ", "Số lượng", "Giá", "Thành tiền"});
        customTableButton1.setHeaderBackgroundColor(new java.awt.Color(153, 153, 255));
        table_CartService.add(customTableButton1, java.awt.BorderLayout.CENTER);

        add(table_CartService, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 550, 180));

        pnl_InforAddService.setBackground(new java.awt.Color(255, 255, 255));
        pnl_InforAddService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pnl_Title_TotalPrice.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Title_TotalPrice.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Tổng tiền:");
        pnl_Title_TotalPrice.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnl_TotalPrice.setBackground(new java.awt.Color(255, 255, 255));
        pnl_TotalPrice.setLayout(new java.awt.BorderLayout());

        lbl_TotalPrice_Value.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_TotalPrice_Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnl_TotalPrice.add(lbl_TotalPrice_Value, java.awt.BorderLayout.CENTER);

        btn_Complete.setText("Hoàn tất");
        btn_Complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CompleteActionPerformed(evt);
            }
        });

        btn_Cancel.setText("Hủy");

        javax.swing.GroupLayout pnl_InforAddServiceLayout = new javax.swing.GroupLayout(pnl_InforAddService);
        pnl_InforAddService.setLayout(pnl_InforAddServiceLayout);
        pnl_InforAddServiceLayout.setHorizontalGroup(
            pnl_InforAddServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_InforAddServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_InforAddServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_InforAddServiceLayout.createSequentialGroup()
                        .addComponent(pnl_Title_TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_TotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_InforAddServiceLayout.createSequentialGroup()
                        .addComponent(btn_Complete, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_InforAddServiceLayout.setVerticalGroup(
            pnl_InforAddServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_InforAddServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_InforAddServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_TotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Title_TotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_InforAddServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Complete, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btn_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(pnl_InforAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 300, 130));

        btn_AddService.setText("Thêm");
        btn_AddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddServiceActionPerformed(evt);
            }
        });
        add(btn_AddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, 30));

        pnl_Title_SelectedService.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Title_SelectedService.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_Title_SelectedService.setForeground(new java.awt.Color(153, 153, 255));
        lbl_Title_SelectedService.setText("Dịch vụ được chọn:");

        javax.swing.GroupLayout pnl_Title_SelectedServiceLayout = new javax.swing.GroupLayout(pnl_Title_SelectedService);
        pnl_Title_SelectedService.setLayout(pnl_Title_SelectedServiceLayout);
        pnl_Title_SelectedServiceLayout.setHorizontalGroup(
            pnl_Title_SelectedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Title_SelectedServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title_SelectedService)
                .addContainerGap(687, Short.MAX_VALUE))
        );
        pnl_Title_SelectedServiceLayout.setVerticalGroup(
            pnl_Title_SelectedServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Title_SelectedServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Title_SelectedService)
                .addContainerGap())
        );

        add(pnl_Title_SelectedService, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 830, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddServiceActionPerformed

    private void btn_CompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CompleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.button.ButtonCustom btn_AddService;
    private ui.components.button.ButtonCancelCustom btn_Cancel;
    private ui.components.button.ButtonCustom btn_Complete;
    private ui.components.table.CustomTableButton customTableButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_RoomID;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_Title_ListService;
    private javax.swing.JLabel lbl_Title_SelectedService;
    private javax.swing.JLabel lbl_TotalPrice_Value;
    private javax.swing.JPanel pnl_InforAddService;
    private javax.swing.JPanel pnl_ListService;
    private javax.swing.JPanel pnl_Search;
    private javax.swing.JPanel pnl_Title;
    private javax.swing.JPanel pnl_Title_ListService;
    private javax.swing.JPanel pnl_Title_SelectedService;
    private javax.swing.JPanel pnl_Title_TotalPrice;
    private javax.swing.JPanel pnl_TotalPrice;
    private javax.swing.JPanel table_CartService;
    private ui.components.table.CustomTableButton table_ListService;
    private ui.components.textfield.SearchTextField txt_SearchServices;
    // End of variables declaration//GEN-END:variables


}
